version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/clean_it
    restart: unless-stopped
    networks:
      - clean_it_network
  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=clean_it
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - clean_it_network

volumes:
  mongo-data:

networks:
  clean_it_network:
    driver: bridge
